name: Build / Test

on:
  push:
  pull_request:

jobs:
  joke:
    runs-on: ubuntu-latest
    steps:
    - name: joke
      run: ls

  build-gradle-project:
    needs: joke
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle Wrapper
      run: ./gradlew build

  actions-timeline:
    needs: [joke,build-gradle-project]
    runs-on: ubuntu-latest
    steps:
      - uses: Kesin11/actions-timeline@v2

